# Sử dụng image Node.js chính thức từ Docker Hub
FROM node:18

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src/app

# Sao chép file package.json và package-lock.json (nếu có)
COPY package*.json ./

# Cài đặt các phụ thuộc của ứng dụng
RUN npm install

# Sao chép tất cả mã nguồn vào container
COPY . .

# Mở cổng 5000 để truy cập ứng dụng
EXPOSE 5000

# Lệnh chạy ứng dụng
CMD ["npm", "start"]
